config/routes.rb
ClearBoxApp::Application.routes.draw do


  #####################################################
  ## Error handling
  #####################################################
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'
  
  
  #####################################################
  ## Home and Index routing
  #####################################################
  root to: "dashboard#index", constraints: lambda { |r| r.env["warden"].authenticate? }
  root :to => 'home#index', :as => 'home'


  #####################################################
  ## One-off pages
  #####################################################
  get 'home_link' => 'home#index'
  get 'about' => 'about#index'
  get 'case_studies' => 'case_studies#index'
  get 'case_studies/:id' => 'case_studies#show', :as => :case_study
  get 'contact' => 'contact#index'
  get 'portfolio' => 'portfolio#index'
  get 'staff' => 'staff#index'
  get 'dashboard' => 'dashboard#index'


  #####################################################
  ## Resources
  #####################################################
  resources :accounts
  resources :events
  resources :jobs


  #####################################################
  ## Mailer routing
  #####################################################
  post 'mailer/contact_us'  => 'mailer#contact_us'


  #####################################################
  ## Admin
  #####################################################
  namespace :admin do
   get 'dashboard' => 'dashboard#index'
  post 'dashboard' => 'dashboard#update'
  end
  
  
  #####################################################
  ## Profiles
  #####################################################
  get 'profiles/search' => 'profiles#search'
  post 'profiles/search' => 'profiles#search'
  resources :profiles, :except => [:create]

  post 'profiles' => 'profiles#index'
  put 'profiles/:id/admin_update'  => 'profiles#admin_update', :as => :profile_admin_update


  #####################################################
  ## User Photos
  #####################################################
  #resources :user_photos
  post 'user/photos/create' => 'user_photos#create'
  post 'user/photos/crop' => 'user_photos#crop'
  post 'user/photos/destroy' => 'user_photos#destroy'
  post 'user/photos/update' => 'user_photos#update'


  #####################################################
  ## User Videos
  #####################################################
  resources :user_videos, :path => "user/videos" do
    get :autocomplete_credit_title, :on => :collection
    get :autocomplete_profile_name_first, :on => :collection
  end

  post 'user/videos/attach_image' => 'user_videos#attach_image'
  post 'user/videos/attach_video' => 'user_videos#attach_video'
  post 'user/videos/crop' => 'user_videos#crop'
  post 'user/videos/destroy' => 'user_videos#destroy'


  #####################################################
  ## Projects and Tasks
  #####################################################

  get 'projects/search' => 'projects#search'
  post 'projects/search' => 'projects#search'

  resources :projects do
    resources :tasks
  end

  get 'tasks' => 'tasks#index', :as => :tasks

  resources :project_videos, :path => "projects/:project_id/videos" do
    get :autocomplete_credit_title, :on => :collection
    get :autocomplete_profile_name_first, :on => :collection
  end

  post 'projects/:project_id/photos/create' => 'project_photos#create'
  post 'projects/:project_id/photos/crop' => 'project_photos#crop'
  post 'projects/:project_id/photos/destroy' => 'project_photos#destroy'
  post 'projects/:project_id/photos/update' => 'project_photos#update'

  post 'projects/:project_id/videos/attach_image' => 'project_videos#attach_image'
  post 'projects/:project_id/videos/attach_video' => 'project_videos#attach_video'
  post 'projects/:project_id/videos/crop' => 'project_videos#crop'
  post 'projects/:project_id/videos/destroy' => 'project_videos#destroy'


  #####################################################
  ## Invoices
  #####################################################
  get 'invoices/search' => 'invoices#search'
  post 'invoices/search' => 'invoices#search'

  resources :invoices
  get 'invoices/:id/pdf' => 'invoices#pdf'
  post 'invoices/send_invoice'


  #####################################################
  ## Users
  #####################################################
  devise_for :users, :skip => [:registrations, :sessions]

  as :user do

    get 'register' => 'registrations#new', :as => :new_user_registration
    post 'register' => 'registrations#create', :as => :user_registration

    get 'password/edit' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'password/edit' => 'devise/registrations#update', :as => :update_user_registration

    delete 'membership/cancel' => 'devise/registrations#destroy', :as => :destroy_user_registration

    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session

  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  ###################################################
  ##  Load the CDN location for photos
  ###################################################
  BACKGROUND_IMAGES_ARRAY = image_names.map { |filename| "#{PORTFOLIO_PATH}#{filename}" }
  
  BACKGROUND_PHRASES = %w[
      home-white-01.svg
      home-white-02.svg
      home-white-03.svg
      home-black-04.svg
  ]

  CDN_CASE_STUDIES_PATH = "#{AWS_CDN_PUBLIC_URL}/case_studies/photos/"

  CASE_STUDIES = {

      'salesforce' => {
          id: 'salesforce',
          title: 'Salesforce.com',
          description: 'Salesforce.com is a global leader in CRM and Cloud computing solutions.
                          When a Chicago team member wanted an updated set of professional  photos,
                          he reached out to Clearbox Studios for options to shoot
                          social profile photos onsite at the office in downtown Chicago.',
          date: 'February 21, 2015',
          image_url: "#{CDN_CASE_STUDIES_PATH}salesforce.jpg"
      },

      'slalom' => {
          id: 'slalom',
          title: 'Slalom Consulting - Rendezvous',
          description: '
    Slalom Consulting is a business and technology consulting firm with offices nation wide. Each local office rewards its
    employees with an annual retreat whose theme, details, and location are left to the individual office and changes every year.',
          date: 'June 01, 2011',
          image_url: "#{CDN_CASE_STUDIES_PATH}slalom.jpg"
      }

  }


  def index
    @background_images = BACKGROUND_IMAGES_ARRAY.shuffle!
    @background_phrases = BACKGROUND_PHRASES.map {|string| 'phrases/' + string}
    @studies = [CASE_STUDIES['salesforce']]
  end

end

app/views/home/index.html.erb
<% @content_frame = "full" %>
<% @page_theme = "dark" %>
<% @menu_hide = true %>

<% content_for :title do %>
    <title>Home</title>
<% end %>


<% content_for :head do %>
    <%= stylesheet_link_tag "home" , :media => 'all' %>
<% end %>

<% content_for :foot do %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.0/jquery.waypoints.min.js"></script>
    <%= javascript_include_tag "home" %>
<% end %>



<div class="columns medium-8 hero">
</div>

<div class="columns medium-4 phrase-container background-black">
  <%= image_tag @background_phrases[0], class: 'background-phrase' %>
</div>


<div class="info">

  <div class="row">
    <div class="column background-gray-light statement">

      <h1 class="text-white text-center line-height-2">
        We provide the <b>tools</b>
        <br>
        that help tell your <b>story</b>.
      </h1>

    </div>

  </div>



  <div class="row">

    <div class="columns medium-4 image-container">
      <div class="background-image" data-image="1"></div>
    </div>

    <div class="columns medium-8 pad-all-3x ">

      <h1 class="orange">
        Photography: Capture the moment.
      </h1>

      <p class="text-white">
        When was the last time you were <b>lost in thought</b> over a special photo?
      </p>

      <p class="text-white">
        We schedule time, hire a <b>professional</b>, make sure everyone looks their best, all for that photo album that will sit
        amongst our prized possessions. Knowing our thoughts, our memories, our happiness, are <b>safe</b> and tucked away.
      </p>

      <p class="text-white">
        Isn't it important to be working with a photographer that appreciates the importance of these fleeting moments?
        Isn't it absolutely <b>vital</b> to know you can trust them to hold hands with your memories?
      </p>

      <%= link_to contact_url do %>
          <button class="button secondary large">Capture the moment</button>
      <% end %>

    </div>

  </div>


  <div class="row">

    <div class="columns medium-4 image-container" >
      <div class="background-image" data-image="2"></div>
    </div>

    <div class="columns medium-8 pad-all-3x ">

      <h1 class="orange">
        Cinematics: Forge the story.
      </h1>

      <p class="text-white">
        The power of motion pictures is <b>rarely</b> described with ease.
      </p>

      <p class="text-white">
        We respond, at our core, to the <b>characters</b> on screen. Fictional or real, stoic or slapstick, familiar or alien.
        Our emotional selves seek out the  <b>emotional</b> in others; we latch onto it and don't let go.
      </p>

      <p class="text-white">
        Those moments, those short-lived  <b>relationships</b> between audience and screen, demand a human respect.
        It requires a  <b>finesse</b>, it requires an understanding, of our deepest flaws and most beautiful truths.
      </p>

      <p class="text-white">
        It is a <b>monument</b> that takes a craftsman to forge.
      </p>

      <%= link_to contact_url do %>
          <button class="button secondary large">Forge your story</button>
      <% end %>

    </div>
  </div>


  <div class="row">
    <div class="columns medium-4 image-container" >
      <div class="background-image" data-image="3"></div>
    </div>

    <div class="columns medium-8 pad-all-3x ">

      <h1 class="orange">
        Motion Graphics: Paint a new reality.
      </h1>

      <p class="text-white">
        Our lives are so pulled by the mundane beauties of the real world.
      </p>

      <p class="text-white">
        The demands of work, family, self are a constant reminder of reality.
        Leaving us constrained by the actualities of physics and psychology.
      </p>

      <p class="text-white">
        What amazing things would we do, if our imaginations were freed? What new sights, what new emotions, could we uncover?
        What new truths about ourselves, about the mundane real world, would we expose?
      </p>

      <p class="text-white">
        It takes a <b>painter</b> to know a canvas when they see one.
      </p>

      <%= link_to contact_url do %>
          <button class="button secondary large">Paint a new reality</button>
      <% end %>

    </div>
  </div>



  <div class="row">
    <div class="column background-gray-light statement">

      <h1 class="text-white text-center line-height-2">
        You have so many <span class="font-heavy">options</span>.
        <br>
        Let's pick the  <span class="font-heavy">right one</span>.
      </h1>

    </div>

  </div>






  <% @studies.each do |study|%>

      <div class="column pad-all-4x background-gray-dark">

        <div class="columns pad-all-4x medium-4">
          <%= image_tag 'clients/' + study[:id] + '.png' %>
        </div>


        <div class="columns medium-8">

          <h1 class="orange">
            Need photos of your team?
            <br>
            So did <%= study[:id].capitalize %>.
          </h1>

          <p class="section-details">
            <%= study[:description] %>
          </p>

          <%= link_to case_study_url(study[:id]) do %>
              <button class="button secondary">View Case Study</button>
          <% end %>

        </div>

      </div>

  <% end %>





  <div class="column pad-all-4x background-gray-light ">

    <div class="columns pad-all medium-4">
      <%= image_tag AWS_CDN_PUBLIC_URL + '/portfolio/eh_01_small.jpg' %>
    </div>


    <div class="columns medium-8">

      <h1 class="orange">
        Earn yourself a finder's fee!
      </h1>

      <p class="text-white">
        Clearbox Studios now offers a client referral plan!
      </p>
      <p class="text-white">
        Any referrals for a photography or video project that result in a booking will earn you a finder's fee:
        you can earn 5-10% of the booking in cash or 10-20% in credit good towards any future work with us.
      </p>
      <p class="text-white">
        So do you know potential clients that need great photo and video work done?
      </p>

      <%= link_to contact_url do %>
          <button class="button secondary large">Contact Us</button>
      <% end %>

    </div>

  </div>


</div>


<!--

<div class="columns medium-4 image-container" >
  <div class="background-image" style="background: url('<%= @background_images[4] %>')"></div>
</div>

<div class="columns medium-8 image-container" >
  <div class="background-image" style="background: url('<%= @background_images[5] %>')"></div>
</div>

-->