config/routes.rb
ClearBoxApp::Application.routes.draw do


  #####################################################
  ## Error handling
  #####################################################
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'
  
  
  #####################################################
  ## Home and Index routing
  #####################################################
  root to: "dashboard#index", constraints: lambda { |r| r.env["warden"].authenticate? }
  root :to => 'home#index', :as => 'home'


  #####################################################
  ## One-off pages
  #####################################################
  get 'home_link' => 'home#index'
  get 'about' => 'about#index'
  get 'case_studies' => 'case_studies#index'
  get 'case_studies/:id' => 'case_studies#show', :as => :case_study
  get 'contact' => 'contact#index'
  get 'portfolio' => 'portfolio#index'
  get 'staff' => 'staff#index'
  get 'dashboard' => 'dashboard#index'


  #####################################################
  ## Resources
  #####################################################
  resources :accounts
  resources :events
  resources :jobs


  #####################################################
  ## Mailer routing
  #####################################################
  post 'mailer/contact_us'  => 'mailer#contact_us'


  #####################################################
  ## Admin
  #####################################################
  namespace :admin do
   get 'dashboard' => 'dashboard#index'
  post 'dashboard' => 'dashboard#update'
  end
  
  
  #####################################################
  ## Profiles
  #####################################################
  get 'profiles/search' => 'profiles#search'
  post 'profiles/search' => 'profiles#search'
  resources :profiles, :except => [:create]

  post 'profiles' => 'profiles#index'
  put 'profiles/:id/admin_update'  => 'profiles#admin_update', :as => :profile_admin_update


  #####################################################
  ## User Photos
  #####################################################
  #resources :user_photos
  post 'user/photos/create' => 'user_photos#create'
  post 'user/photos/crop' => 'user_photos#crop'
  post 'user/photos/destroy' => 'user_photos#destroy'
  post 'user/photos/update' => 'user_photos#update'


  #####################################################
  ## User Videos
  #####################################################
  resources :user_videos, :path => "user/videos" do
    get :autocomplete_credit_title, :on => :collection
    get :autocomplete_profile_name_first, :on => :collection
  end

  post 'user/videos/attach_image' => 'user_videos#attach_image'
  post 'user/videos/attach_video' => 'user_videos#attach_video'
  post 'user/videos/crop' => 'user_videos#crop'
  post 'user/videos/destroy' => 'user_videos#destroy'


  #####################################################
  ## Projects and Tasks
  #####################################################

  get 'projects/search' => 'projects#search'
  post 'projects/search' => 'projects#search'

  resources :projects do
    resources :tasks
  end

  get 'tasks' => 'tasks#index', :as => :tasks

  resources :project_videos, :path => "projects/:project_id/videos" do
    get :autocomplete_credit_title, :on => :collection
    get :autocomplete_profile_name_first, :on => :collection
  end

  post 'projects/:project_id/photos/create' => 'project_photos#create'
  post 'projects/:project_id/photos/crop' => 'project_photos#crop'
  post 'projects/:project_id/photos/destroy' => 'project_photos#destroy'
  post 'projects/:project_id/photos/update' => 'project_photos#update'

  post 'projects/:project_id/videos/attach_image' => 'project_videos#attach_image'
  post 'projects/:project_id/videos/attach_video' => 'project_videos#attach_video'
  post 'projects/:project_id/videos/crop' => 'project_videos#crop'
  post 'projects/:project_id/videos/destroy' => 'project_videos#destroy'


  #####################################################
  ## Invoices
  #####################################################
  get 'invoices/search' => 'invoices#search'
  post 'invoices/search' => 'invoices#search'

  resources :invoices
  get 'invoices/:id/pdf' => 'invoices#pdf'
  post 'invoices/send_invoice'


  #####################################################
  ## Users
  #####################################################
  devise_for :users, :skip => [:registrations, :sessions]

  as :user do

    get 'register' => 'registrations#new', :as => :new_user_registration
    post 'register' => 'registrations#create', :as => :user_registration

    get 'password/edit' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'password/edit' => 'devise/registrations#update', :as => :update_user_registration

    delete 'membership/cancel' => 'devise/registrations#destroy', :as => :destroy_user_registration

    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session

  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController



  ################################################
  # Filters
  ################################################
  before_filter :authenticate_user!




  ################################################
  # GET /projects
  # GET /projects.json
  ################################################

  def index

    results = Project.includes(:images, :videos, :account, :invoice).user_readable(current_user)

    respond_to do |format|

      if results.size == 1
        @project = results.first
        format.html { redirect_to project_url(@project)}

      else
        @projects = results.page(params[:page]).per(@@results_per_page)
        format.html # index.html.erb
      end

    end

  end


  ################################################
  # GET /projects/1
  # GET /projects/1.json
  ################################################

  def show

    @project = Project.includes(:account, :images, :videos, :invoice).user_readable(current_user, params[:id])

    if @project

      begin
        @photos = []
        @videos = []

        if @project.user_editable(current_user)

          @video_player_type = 'editable'
        else

          @video_player_type = 'playable'
        end

        if @project.invoice.nil?
          @invoice = false
        else
          @invoice = @project.invoice.user_readable(current_user)
        end


      rescue
        @media_by_project = {}
        network_error
      end

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @project }
      end

    else
      not_authorized
    end


  end



  ################################################
  # GET /projects/new
  # GET /projects/new.json
  ################################################

  def new

    @original_project_id = ''
    @accounts =  []

    if Account.user_readable(current_user).any?

      if params[:original_project_id]
        @original_project = Project.user_readable(current_user, params[:original_project_id])
        @project = @original_project.dup

        @accounts << @project.account
        @accounts = @accounts +  Account.user_readable(current_user)
        @accounts.reverse!
        @accounts.uniq!
        @accounts.reverse!

      elsif params[:account_id]
        @account = Account.user_readable(current_user, params[:account_id])
        @project = @account.projects.new

        @accounts << @project.account
        @accounts = @accounts +  Account.user_readable(current_user)
        @accounts.reverse!
        @accounts.uniq!
        @accounts.reverse!

      else
        @project = Project.new
        @accounts =  Account.user_readable(current_user)

      end


      respond_to do |format|
        format.html # edit.html.erb
        format.json { render json: @project }
      end

    else

      respond_to do |format|
        format.html { redirect_to new_account_url, notice: 'Please create a billable account first.' }
      end

    end


  end



  ################################################
  # GET /projects/1/edit
  ################################################

  def edit

    @project = Project.user_readable(current_user, params[:id])

    if @project
      @accounts =  []
      @accounts << @project.account
      @accounts = @accounts +  Account.user_readable(current_user)
      @accounts.reverse!
      @accounts.uniq!
      @accounts.reverse!

    else
      not_authorized
    end

  end


  ################################################
  # POST /projects
  # POST /projects.json
  ################################################

  def create

    ## Format the date/time, otherwise the incoming values are ignored during update throw validation errors
    params[:project][:start]= Date.strptime(params[:project][:start], '%m-%d-%Y')
    params[:project][:end]= Date.strptime(params[:project][:end], '%m-%d-%Y')

    @original_project = Project.user_editable(current_user, params[:original_project_id]) if params[:original_project_id]
    @project = Project.new(params[:project])

    respond_to do |format|

      if @original_project && @project.save && @project.create_duplicate_tasks(@original_project)
        format.html { redirect_to project_url(@project), notice: 'Project "' + @project.title + '" was successfully created.' }
        format.json { render json: project_url(@project), status: :created, location: @project }

      elsif @project.save && @project.create_default_tasks
        format.html { redirect_to project_url(@project), notice: 'Project "' + @project.title + '" was successfully created.' }
        format.json { render json: project_url(@project), status: :created, location: @project }

      else
        @accounts = Account.user_readable(current_user)
        format.html { render action: "new"}
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  ################################################
  # PUT /projects/1
  # PUT /projects/1.json
  ################################################

  def update

    @project = Project.user_editable(current_user, params[:id])

    ## Format the date/time, otherwise the incoming values are ignored during update throw validation errors
    params[:project][:start]= Date.strptime(params[:project][:start], '%m-%d-%Y')
    params[:project][:end]= Date.strptime(params[:project][:end], '%m-%d-%Y')


    if @project
      respond_to do |format|

        if @project.update(params[:project])
          format.html { redirect_to project_url(@project), notice: 'Project "' + @project.title + '" was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end

      end

    else
      not_authorized
    end

  end


  ################################################
  # POST /projects
  # POST /projects.json
  ################################################

  def search

    @searching = true
    results = Project.includes(:images, :videos, :account, :invoice).user_readable(current_user).search_for(params['search-string'])
    @projects = results.page(params[:page]).per(@@results_per_page)

    respond_to do |format|
      format.html { render action: "index" }
      format.json { render json: @project.errors, status: :unprocessable_entity }
    end

  end


  ################################################
  # DELETE /projects/media
  # DELETE /projects.json
  ################################################
  def delete_media

    @asset = Asset.find(params[:id])
    @asset.destroy
    flash[:notice] = "Project files have been deleted"

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Files have been deleted.' }
    end

  end



  ################################################
  # DELETE /projects/1
  # DELETE /projects/1.json
  ################################################

  def destroy

    @project = Project.find(params[:id])
    @project.destroy if @project.destroyable? && Project.user_editable(current_user).include?(@project)
    account_param = {:account_id=> params[:account_id]} unless params[:account_id].nil?

    respond_to do |format|
      format.html { redirect_to projects_url(account_param) }
      format.json { head :no_content }
    end

  end







  private


  ################################################
  # Class Variables
  ################################################


  def find_media(projects)

    begin

      media_by_project = {}

      projects.each do |project|

        src_url = project.image_url(:medium)
        download_url = project.image_url(:medium)


        @bucket_objects = project.bucket_objects('documents')
        bucket_count = @bucket_objects.count
        @bucket_objects.each do |object|

          if object.content_type.split("/").first == 'image'
            src_url = object.url_for(:read, secure: true, expires: 90.minutes).to_s
            download_url = object.url_for(:read, secure: true, expires: 90.minutes, response_content_disposition: 'attachment;').to_s
            break
          end
        end


        media_by_project[project]= {count: bucket_count, src_url: src_url, download_url: download_url}

      end

    rescue
      network_error
    end


    return media_by_project

  end







end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= render '/layouts/form_errors', :model => @project %>


<%= form_for @project, data: {abide: ''}, :html => {:class => 'space-above'} do |f| %>

    <% if original_project_id %>
        <%= hidden_field_tag :original_project_id, original_project_id %>
    <% end %>


    <div class="row no-child-padding">
      <div class="columns medium-5">

        <%= f.label :title %>
        <%= f.text_field :title, required: '' %>


        <%= f.label :account %>
        <% if @project.invoice.nil? %>
            <%= f.collection_select :account_id, @accounts, :id, :name, :prompt => "Select an account" %>
        <% else %>
            <%= text_field_tag 'project_account_name', @project.account.name, disabled: true %>
        <% end %>


        <%= f.label :description %>
        <%= f.text_area :description, required: '' %>

        <div class="row no-child-padding">

          <%= f.label :start %>
          <div class="row date collapse fdatepicker" data-date-format="mm-dd-yyyy">
            <div class="small-10 columns">
              <%= f.text_field :start, :id => 'date-start', :value => @project.start.nvl(Date.today).strftime("%m-%d-%Y") %>
            </div>
            <div class="small-2 columns">
              <label class="postfix icon-calendar-31 inline"></label>
            </div>
          </div>

          <%= f.label :end %>
          <div class="row date collapse fdatepicker" data-date-format="mm-dd-yyyy">
            <div class="small-10 columns">
              <%= f.text_field :end, :id => 'date-end', :value => @project.end.nvl(Date.today).strftime("%m-%d-%Y") %>
            </div>
            <div class="small-2 columns">
              <label class="postfix icon-calendar-31 inline"></label>
            </div>
          </div>
        </div>

      </div>

      <div class="columns medium-6">
        <%= f.label :category %>
        <ul class="small-up-2 space-below-2x">
          <% Project::ENUMERATIONS[:categories].each do |value| %>
              <li><%= radio_box f, 'category', value %></li>
          <% end %>
        </ul>

        <%= f.label :status %>
        <ul class="small-up-2">
          <% Project::ENUMERATIONS[:status].each do |value| %>
              <li><%= radio_box f, 'status', value %></li>
          <% end %>
        </ul>

      </div>

    </div>

    <div class="row submission">
      <%= f.submit :class => "button white bordered space-above-2x" %>
    </div>

<% end %>

app/views/projects/_toolbar.html.erb
<div class="toolbar button-group">


  <% if @invoice == false %>
      <%= link_to(raw('<i class="icon-doc-alt"></i>NOT INVOICED'), '#', class: 'button tiny clear disabled', title:  'not yet invoiced') %>

  <% elsif @invoice.nil? %>
      <%= link_to(raw('<i class="icon-doc-alt"></i>INVOICED'), '#', class: 'button tiny clear disabled', title:  'view invoice') %>

  <% else  %>
      <%= link_to(raw('<i class="icon-doc-alt"></i>INVOICED'), invoice_url(@project.invoice), class: 'button tiny clear', title:  'view invoice') %>
  <% end %>


  <% if current_user.staff_member? %>
      <%= link_to raw('<i class="icon-edit"></i>EDIT'), edit_project_url(@project), class: 'button tiny clear', title:  'edit invoice' %>
      <%= link_to raw('<i class="icon-docs"></i>DUPLICATE'), new_project_url(:original_project_id => @project), class: 'button tiny clear',  title:  'duplicate invoice' %>

      <%= link_to raw('<i class="icon-trash-1"></i>DELETE'),
                  project_url(@project, account_id: @project.account.id),
                  confirm:  'Once deleted this project CANNOT be recovered.<br><br> Are you sure you want to remove it permanently?',
                  method: 'delete',
                  class: 'button tiny clear hover-red',
                  id: 'toolbar_delete_' + @project.id.to_s,
                  title:  'delete project' %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<% content_for :title do %>
    <title><%= @project.title %></title>
<% end %>

<% content_for :head do %>
    <%= stylesheet_link_tag "projects" , :media => 'all' %>
    <link media="all" rel="stylesheet" type="text/css" href="/plugins/foundation-datepicker-master/stylesheets/foundation-datepicker.css" />
<% end %>


<% content_for :foot do %>
    <%= javascript_include_tag "/plugins/foundation-datepicker-master/js/foundation-datepicker.js" %>
    <script type="text/javascript" >
        $(document).ready(function () {
            $('.fdatepicker').fdatepicker();
        });
    </script>
<% end %>


<% @breadcrumbs = {history: [{text: 'Projects', url: projects_url}, {text: @project.title, url: project_url(@project)}], current: 'Edit'} %>
<%= render 'layouts/breadcrumb' %>



<h1 class='orange space-below-2x'>Edit Project</h1>




<!--  Editing Form  -->
<!--------------------------------------------->
<%= render 'form', original_project_id: @original_project_id %>

app/views/projects/index.html.erb
<% content_for :title do %>
    <title>Your Projects</title>
<% end %>

<% content_for :head do %>
    <%= stylesheet_link_tag "projects" , :media => 'all' %>
<% end %>

<% content_for :foot do %>
<% end %>


<% if @searching %>
    <% @breadcrumbs = {history: [{text: 'Projects', url: projects_url}], current: 'SEARCH'} %>
<% else %>
    <% @breadcrumbs = {current: 'projects'} %>
<% end %>
<%= render 'layouts/breadcrumb' %>


<h1 class='orange'>Your Projects</h1>
<div class='section-details'>
  <h5>Click a project below to view status details.</h5>
</div>


<%= render 'layouts/searchbox', search_url: '/projects/search', placeholder: 'Search for projects' %>

<%= render 'layouts/paginate', pagination_object: @projects %>



<div class="search-results">

  <% @projects.each do |project|%>


      <div class="row column results-item">

        <div class="search-thumbnail">
          <%= link_to project_url(project) do %>
              <%= image_tag(project.image_url(:medium), class: '' ) %>
          <% end %>
        </div>

        <div class="results-content">

          <%= link_to project_url(project) do %>
              <h4 class="orange"><%= project.title %></h4>
          <% end %>

          <p><%= project.description %></p>


        </div>

        <div class="results-stats">
          <span class="results-stat">Account: <%= link_to project.account.name, account_url(project.account) %></span>
          <span class="results-stat">Invoice ID:
            <% if project.invoice %>
                    <%= link_to project.invoice.id, invoice_url(project.invoice) %>
            <% end %>

          </span>
          <span class="results-stat"><b><%= project.images.size.to_s %> photos</b></span>
          <span class="results-stat"><b><%= project.videos.size.to_s %> videos</b></span>
          <span class="results-stat"><%= project.status %></span>
          <span class="results-stat"><%= project.updated_at.strftime('%b %d, %Y') %></span>




        </div>

      </div>


  <% end %>

</div>

app/views/projects/new.html.erb
<% content_for :title do %>
    <title>New Project</title>
<% end %>

<% content_for :head do %>

    <%= stylesheet_link_tag "projects" , :media => 'all' %>
    <link media="all" rel="stylesheet" type="text/css" href="/plugins/foundation-datepicker-master/stylesheets/foundation-datepicker.css" />
<% end %>


<% content_for :foot do %>
    <%= javascript_include_tag "/plugins/foundation-datepicker-master/js/foundation-datepicker.js" %>
    <script type="text/javascript" >
        $(document).ready(function () {
            $('.fdatepicker').fdatepicker();
        });
    </script>

    <%= javascript_include_tag "image-gallery" %>
<% end %>



<% @breadcrumbs = {history: [{text: 'Projects', url: projects_url}], current: 'New Project'} %>
<%= render 'layouts/breadcrumb' %>


<h1 class='orange space-below-2x'>New Project</h1>



<!--  Editing Form  -->
<!--------------------------------------------->
<%= render 'form', :original_project_id => @original_project_id %>

app/views/projects/old.index.html.erb
<% #@background_opacity_class = 'transparent' %>
<% @content_frame = 'wide-with-sidebar' %>

<% content_for :title do %>
    <title>Projects</title>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag "image-gallery" %>
  <%= stylesheet_link_tag "projects" , :media => 'all' %>  
<% end %>


  <!--  Breadcrumbs  -->
  <!--------------------------------------------->
  <div class="breadcrumb">
    <% if params[:account_id] %>
      <%= link_to(@account.name + ' account', accounts_url) + ' / ' %> 
    <% end %>
  </div>
  

  <!--  Searchbar  -->
  <!--------------------------------------------->
  <%= form_tag '/projects/search', :method => :post do %>
    <%= text_field_tag 'search-string', nil, :placeholder => 'Search for projects' %>
    <%= submit_tag nil, :class => 'button hoverable', :id=>'search-submit' %>
  <% end %>  




  <% @projects.each do |project| %>


    <!--  Project container  -->
    <!--------------------------------------------->
      <div class='orange'>
      
          <%= link_to project do %>
            <h2 class='list-header'><%= project.title %></h2>
          <% end %>    

          <!-- toolbar  -->
          <!--------------------------------------------->
          <div id="<%= 'toolbar_' + project.id.to_s %>" class="toolbar">
            <%= link_to raw('<i class="icon-folder-open-empty"></i>'), project_url(project), :id=>'toolbar_project_' + project.id.to_s, :title=>'project details' %>
            <%= link_to raw('<i class="icon-pencil-neg"></i>'), edit_project_url(project) , :id=>'toolbar_edit_' + project.id.to_s, :title=>'edit project' %>
            <%= link_to raw('<i class="icon-docs"></i>'), new_project_url(:account_id => params[:account_id], :original_project_id => project.id) , :id=>'toolbar_duplicate_' + project.id.to_s, :title=>'duplicate project and tasks' %>
            <%= link_to(raw('<i class="icon-doc-alt"></i>'), invoice_url(project.invoice) , :id=>'toolbar_invoice_' + project.id.to_s, :title=>'view invoice') unless project.invoice.nil?  %>
            <%= link_to raw('<i class="icon-cancel"></i>'), project_url(project,:account_id => params[:account_id]), :confirm => 'Once deleted this project CANNOT be recovered.<br><br> Are you sure you want to remove it permanently?', :method => :delete , :id=>'toolbar_delete_' + project.id.to_s, :title=>'delete project' %>
          </div>

      </div>
    
    
      <div class='floating-container multi-column'>
        <%= link_to project, :style=> 'display:block;', :title=>'project details' do %>
          <%= image_tag project.image_url(:medium), :alt => project.title, :class=>'search-results' , :style=>'float:none;' %>
        <% end %>
      </div>
      
      <div class='floating-container multi-column' style='max-width:42em;'>
      
          <div class='floating-container multi-column' style='min-height: 3em; margin-top:0; max-width:90%;' >

              <b>DESCRIPTION:</b> 
              <span class='section-details'>
                <%= project.description.first(225)  %>
              </span>
          </div>


          <!--  Project Information  -->
          <!--------------------------------------------->
          <span class='floating-container multi-column' style='clear:left;max-width: 15em;'>
            <b>PROJECT INFORMATION</b>
            <br>
            <span class='section-details'>
              <label>category: </label><%= project.category  %>
              <br>
              <label>start date: </label><%= project.start  %>
              <br>
              <label>end date: </label><%= project.end  %>
              <br>          
            </span>
          </span>



          <!--  Billing Information  -->
          <!--------------------------------------------->
          <span class='floating-container multi-column' style='max-width: 15em;'>
            <b>BILLING INFORMATION</b>
            <br>
            <span class='section-details'>
              <label>billed to: </label><%= project.account.name %>
              <br>
              <label>invoice #: </label><%=  project.invoice.nil?? '' : project.invoice.id %>
              <br>
              <label>status: </label><%= project.status  %>
            </span>
          </span>


          <!--  Task Information  -->
          <!--------------------------------------------->
          <span class='floating-container multi-column' style='max-width: 15em;'>
            <b>TASK INFORMATION</b>
            <br>
            <span class='section-details'>
              <% Task::CATEGORY_ENUM.each do |category| %>
                <label><%= category.downcase %>: </label><%= project.tasks.where(:category => category).count  %>
                <br>
              <% end %>
                <label>total: </label><%= project.tasks.count  %>
            </span>
          </span>

      </div>
  <% end %>

app/views/projects/show.html.erb
<% content_for :title do %>
    <title><%= @project.title %></title>
<% end %>

<% content_for :head do %>
    <%= stylesheet_link_tag "projects" , :media => 'all' %>
<% end %>


<% @breadcrumbs = {history: [{text: 'Projects', url: projects_url}], current: @project.title} %>
<%= render 'layouts/breadcrumb' %>

<%= render 'toolbar' %>

<h1 class='orange space-above'><%= @project.title %></h1>

<div class="row column model-details">
    <span class="model-stats">
      <div class="title"><p>Account</p></div>
      <div class="content"><h5><%=  @project.account.name %></h5></div>
    </span>


    <span class="model-stats">
      <div class="title"><p>Start</p></div>
      <div class="content"><h5><%=  @project.start %></h5></div>
    </span>


    <span class="model-stats">
      <div class="title"><p>End</p></div>
      <div class="content"><h5><%=  @project.end %></h5></div>
    </span>

    <span class="model-stats">
      <div class="title"><p>Status</p></div>
      <div class="content"><h5><%=  @project.status %></h5></div>
    </span>
</div>

<h3 class='orange space-above'>Description</h3>
<p><%= @project.description %></p>


<% if @project.images.any? %>

    <h3 class='orange space-above-2x'>Photos</h3>

    <div class="row column">
      <ul class="image-gallery-grid small-up-3 medium-up-5">
        <%= render 'layouts/image_gallery', gallery_model: 'projects', images: @project.images, downloadable: true, type: 'viewable' %>
      </ul>
    </div>

    <a id="download_all" class="button medium clear float-right"><i class="icon-download-cloud"></i> Download All Photos</a>
<% end %>


<% if @project.videos.any? %>

    <h3 class='orange space-above-2x'>
      Videos
    </h3>

    <div class="video-gallery">
      <%= render 'layouts/video_gallery', profile: Profile.first, videos: @project.videos, type: @video_player_type %>
    </div>

<% end %>


<% if  @user_editable and (@project.images.any? or @project.videos.any?) %>
    <%= render 'layouts/photo_crop', photo_to_crop_id: '', fullsize_photo_url: '' %>
<% end %>