config/routes.rb
ClearBoxApp::Application.routes.draw do


  #####################################################
  ## Error handling
  #####################################################
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'
  
  
  #####################################################
  ## Home and Index routing
  #####################################################
  root to: "dashboard#index", constraints: lambda { |r| r.env["warden"].authenticate? }
  root :to => 'home#index', :as => 'home'


  #####################################################
  ## One-off pages
  #####################################################
  get 'home_link' => 'home#index'
  get 'about' => 'about#index'
  get 'case_studies' => 'case_studies#index'
  get 'case_studies/:id' => 'case_studies#show', :as => :case_study
  get 'contact' => 'contact#index'
  get 'portfolio' => 'portfolio#index'
  get 'staff' => 'staff#index'
  get 'dashboard' => 'dashboard#index'


  #####################################################
  ## Resources
  #####################################################
  resources :accounts
  resources :events
  resources :jobs


  #####################################################
  ## Mailer routing
  #####################################################
  post 'mailer/contact_us'  => 'mailer#contact_us'


  #####################################################
  ## Admin
  #####################################################
  namespace :admin do
   get 'dashboard' => 'dashboard#index'
  post 'dashboard' => 'dashboard#update'
  end
  
  
  #####################################################
  ## Profiles
  #####################################################
  get 'profiles/search' => 'profiles#search'
  post 'profiles/search' => 'profiles#search'
  resources :profiles, :except => [:create]

  post 'profiles' => 'profiles#index'
  put 'profiles/:id/admin_update'  => 'profiles#admin_update', :as => :profile_admin_update


  #####################################################
  ## User Photos
  #####################################################
  #resources :user_photos
  post 'user/photos/create' => 'user_photos#create'
  post 'user/photos/crop' => 'user_photos#crop'
  post 'user/photos/destroy' => 'user_photos#destroy'
  post 'user/photos/update' => 'user_photos#update'


  #####################################################
  ## User Videos
  #####################################################
  resources :user_videos, :path => "user/videos" do
    get :autocomplete_credit_title, :on => :collection
    get :autocomplete_profile_name_first, :on => :collection
  end

  post 'user/videos/attach_image' => 'user_videos#attach_image'
  post 'user/videos/attach_video' => 'user_videos#attach_video'
  post 'user/videos/crop' => 'user_videos#crop'
  post 'user/videos/destroy' => 'user_videos#destroy'


  #####################################################
  ## Projects and Tasks
  #####################################################

  get 'projects/search' => 'projects#search'
  post 'projects/search' => 'projects#search'

  resources :projects do
    resources :tasks
  end

  get 'tasks' => 'tasks#index', :as => :tasks

  resources :project_videos, :path => "projects/:project_id/videos" do
    get :autocomplete_credit_title, :on => :collection
    get :autocomplete_profile_name_first, :on => :collection
  end

  post 'projects/:project_id/photos/create' => 'project_photos#create'
  post 'projects/:project_id/photos/crop' => 'project_photos#crop'
  post 'projects/:project_id/photos/destroy' => 'project_photos#destroy'
  post 'projects/:project_id/photos/update' => 'project_photos#update'

  post 'projects/:project_id/videos/attach_image' => 'project_videos#attach_image'
  post 'projects/:project_id/videos/attach_video' => 'project_videos#attach_video'
  post 'projects/:project_id/videos/crop' => 'project_videos#crop'
  post 'projects/:project_id/videos/destroy' => 'project_videos#destroy'


  #####################################################
  ## Invoices
  #####################################################
  get 'invoices/search' => 'invoices#search'
  post 'invoices/search' => 'invoices#search'

  resources :invoices
  get 'invoices/:id/pdf' => 'invoices#pdf'
  post 'invoices/send_invoice'


  #####################################################
  ## Users
  #####################################################
  devise_for :users, :skip => [:registrations, :sessions]

  as :user do

    get 'register' => 'registrations#new', :as => :new_user_registration
    post 'register' => 'registrations#create', :as => :user_registration

    get 'password/edit' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'password/edit' => 'devise/registrations#update', :as => :update_user_registration

    delete 'membership/cancel' => 'devise/registrations#destroy', :as => :destroy_user_registration

    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session

  end


end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def assign_constants
  end

  def index
    assign_constants
    @staff_users = User.staff_members.includes(:profile, :photos).sort_by(&:id)
  end


end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/index.html.erb
<% @content_frame = "thin" %>
<% @menu_hide = true %>



<% content_for :title do %>
    <title>About Clearbox Studios</title>
<% end %>

<% content_for :head do %>
    <%= stylesheet_link_tag "about", :media => 'all' %>
<% end %>

<% content_for :foot do %>
<% end %>


<% @breadcrumbs = {current: 'About'} %>
<%= render 'layouts/breadcrumb' %>


<div class="hero-container">
  <div class="hero-image ninth"></div>
  <div class="hero-image eh"></div>
  <div class="hero-image panasonic"></div>

</div>



<div class="row data-equalizer" data-equalizer data-equalize-on="medium" >
  <div class="columns medium-6 large-5 callout-container">

    <div class="columns small-centered callout-details" data-equalizer-watch>

      <h2 class="text-center space-above-2x">WHO WE ARE</h2>

      <div class="row space-above">

        <div class="columns callout-number">
          <h3>Chicago</h3>
        </div>

        <div class="columns callout-description">
          born and raised, work and play
        </div>

      </div>

      <div class="row space-above-2x">

        <div class="columns callout-number">
          <h3>2006</h3>
        </div>

        <div class="columns callout-description">
          the year we started
        </div>

      </div>

      <div class="row space-above-2x">

        <div class="columns callout-number large">
          <h3>the color of bruises</h3>
        </div>

        <div class="columns callout-description">
          our first feature length film
        </div>

      </div>

      <div class="row space-above-2x">

        <div class="columns callout-number">
          <h3>36,045</h3>
        </div>

        <div class="columns callout-description">
          total number of photos taken
        </div>
      </div>

    </div>

  </div>


  <div class="columns medium-6 large-7 study-description" data-equalizer-watch>


    <h2 class="orange space-above-2x">Our Style</h2>
    <p>
      We specialize in cogent, collaborative, and creative content across all media.
      In other words, we work clearly, we work as a team, and we work to be unique.
      We aren't looking to deliver the same content you can get elsewhere;
      our clients look to our expertise, our creative eyes, and our passion to get the job done well.
    </p>


    <h2 class="orange space-above">Our Process</h2>
    <p>
      Our process targets written and audiovisual production that delivers content.
      We thrive on providing a unique service that cannot be found elsewhere.
      We are addicted to creating, building, producing content that always hits its mark.
      Head over to our <%= link_to 'Portfolio', portfolio_url, class:'orange underlined-links' %>
      to see a very small sample of our favorite wins.
    </p>


    <h2 class="orange space-above">Our Promise</h2>
    <p>
      Client satisfaction and over-delivery are part of our daily work.
      We have something to prove, and we want you to be a part of that ride.
      It doesn't matter if your project needs to be entertaining, educational, informational, promotional,
      or something else entirely... we've got you covered.
    </p>
    <p>
      Take a look at our
      <%= link_to 'Case Studies', case_studies_url, class:'orange underlined-links' %>
      to get an idea of what new projects we can help lift off the ground for you.
    </p>

  </div>

</div>




<div class="row column space-above-4x">

  <h2 class="orange">Some Of Our Team</h2>


  <div class="row medium-up-2 large-up-3">

    <% @staff_users.each do |staff_member| %>

        <div class="column">
          <%= render 'layouts/social_thumbnail', profile: staff_member.profile %>
        </div>
    <% end %>

  </div>

</div>